---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Set configuration for ntp.conf living internal to RH
      copy:
        src: files/chrony.conf
        dest: /etc/chrony.conf
    - name: Start and enable ntp service
      systemd:
        name: chronyd.service
        state: restarted
        enabled: yes

